CREATE TABLE IF NOT EXISTS player_research_metrics (
  id              SERIAL PRIMARY KEY,
  player_id       INTEGER NOT NULL REFERENCES players(id),
  season          INTEGER NOT NULL,
  as_of_date      DATE NOT NULL,
  games_played    INTEGER NOT NULL DEFAULT 0,
  starter_pct     DECIMAL(5,4),
  avg_min         DECIMAL(5,2),
  avg_pts         DECIMAL(5,2),
  avg_reb         DECIMAL(5,2),
  avg_ast         DECIMAL(5,2),
  avg_stl         DECIMAL(5,2),
  avg_blk         DECIMAL(5,2),
  avg_tov         DECIMAL(5,2),
  avg_fg3m        DECIMAL(5,2),
  avg_pra         DECIMAL(5,2),
  avg_stl_blk     DECIMAL(5,2),
  avg_usage_rate  DECIMAL(5,4),
  l3_min          DECIMAL(5,2),
  l3_pts          DECIMAL(5,2),
  l3_reb          DECIMAL(5,2),
  l3_ast          DECIMAL(5,2),
  l3_stl          DECIMAL(5,2),
  l3_blk          DECIMAL(5,2),
  l3_tov          DECIMAL(5,2),
  l3_fg3m         DECIMAL(5,2),
  l5_min          DECIMAL(5,2),
  l5_pts          DECIMAL(5,2),
  l5_reb          DECIMAL(5,2),
  l5_ast          DECIMAL(5,2),
  l5_stl          DECIMAL(5,2),
  l5_blk          DECIMAL(5,2),
  l5_tov          DECIMAL(5,2),
  l5_fg3m         DECIMAL(5,2),
  l10_min         DECIMAL(5,2),
  l10_pts         DECIMAL(5,2),
  l10_reb         DECIMAL(5,2),
  l10_ast         DECIMAL(5,2),
  l10_stl         DECIMAL(5,2),
  l10_blk         DECIMAL(5,2),
  l10_tov         DECIMAL(5,2),
  l10_fg3m        DECIMAL(5,2),
  home_avg_pts    DECIMAL(5,2),
  home_avg_reb    DECIMAL(5,2),
  home_avg_ast    DECIMAL(5,2),
  home_avg_min    DECIMAL(5,2),
  away_avg_pts    DECIMAL(5,2),
  away_avg_reb    DECIMAL(5,2),
  away_avg_ast    DECIMAL(5,2),
  away_avg_min    DECIMAL(5,2),
  pts_std_dev     DECIMAL(5,2),
  reb_std_dev     DECIMAL(5,2),
  ast_std_dev     DECIMAL(5,2),
  min_std_dev     DECIMAL(5,2),
  min_consistency_score DECIMAL(5,2),
  pts_trend       VARCHAR(20),
  reb_trend       VARCHAR(20),
  ast_trend       VARCHAR(20),
  min_trend       VARCHAR(20),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(player_id, season, as_of_date)
);

CREATE INDEX IF NOT EXISTS idx_prm_player_id ON player_research_metrics(player_id);
CREATE INDEX IF NOT EXISTS idx_prm_season ON player_research_metrics(season);
CREATE INDEX IF NOT EXISTS idx_prm_player_season ON player_research_metrics(player_id, season, as_of_date DESC);
